#!/bin/bash

########## INSTALLATION-SCRIPT ##########
if [ "$(id -u)" -ne 0 ]; then echo 'Please run as root.' >&2; exit 1; fi

VoidPreChroot () {
  echo 'start with void'
  for dir in dev proc sys run; do 
    mkdir -p /mnt/$dir
    mount --rbind /$dir /mnt/$dir
    mount --make-rslave /mnt/$dir
  done
  mount -t devpts pts /mnt/dev/pts
  REPO=https://alpha.de.repo.voidlinux.org/current
  ARCH=x86_64
  xbps-install -Su xbps
  XBPS_ARCH=$ARCH xbps-install -S -r /mnt -R "$REPO" nano base-system linux linux-firmware $btrfsdep
}

VoidInChroot () {
  cp /etc/resolv.conf /mnt/etc/
  chroot /mnt xbps-install -Sy void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree
  chroot /mnt xbps-install -S intel-ucode
  echo -e "# /etc/rc.conf - system configuration for void
HOSTNAME=$UNSel
HARDWARECLOCK=UTC
TIMEZONE=$TZSel
$keylayout" >> /etc/rc.rc.conf
  
  chroot /mnt echo 'en_US.UTF-8 UTF-8' > /etc/default/libc-locales
  chroot /mnt echo LANG=en_US.UTF-8 > /etc/locale.conf
  
}

CheckAS () {
  if [[ -f "$(pwd)/additional_setup" && -f "$(pwd)/pkg_checker" ]]; then
    source additional_setup
    source pkg_checker
  else
    echo "Missing file: additional_setup"
    exit 1
  fi
  echo 'done with addsetup'
}

DiskPartition () {
  umount -R /mnt 
  "$pkgmanager" -Sy "${pkgskips[@]}" parted gptfdisk mtools ntfs-3g dialog
  devicelist="$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)"
  DRIVE="$(dialog --stdout --menu "Select disk for installation" 0 0 0 ${devicelist} || exit 1)"
  EXT_DRIVE="$(dialog --stdout --menu "Select EXTERNAL disk" 0 0 0 ${devicelist} || exit 1)"
  ##parted -s "mklabel gpt mkpart ESP fat32 1MiB 512MiB mkpart root ext4 512MiB 100% set 1 esp on"
  #parted -s "$DRIVE" mklabel gpt mkpart "EFI system partition" 0% 1% set 1 esp on mkpart "root partition" 1% 100% set 1 esp on
  #echo "$DRIVE"
  sgdisk --zap-all \
  --clear \
  --new=1:0:+550M --typecode=1:ef00 \
  --new=2:0:0 --typecode=2:8300 \
  "$DRIVE"
  sgdisk --verify "$DRIVE"
  if echo "$DRIVE" | grep "^/dev/[a-z]d[a-z]"; then 
  BOOT_PART="$DRIVE"1 && ROOT_PART="$DRIVE"2
  DEVICE="sda"
  elif echo "$DRIVE" | grep "^/dev/nvme"; then 
  BOOT_PART="$DRIVE"p1 && ROOT_PART="$DRIVE"p2
  DEVICE="nvme0n1"
  elif echo "$DRIVE" | grep "^/dev/mmc"; then 
  BOOT_PART="$DRIVE"1 && ROOT_PART="$DRIVE"2
  DEVICE="mmc"
  fi

  BOOTID="$(blkid -s "$PIDSel" -o value "$BOOT_PART")"
  ROOTID="$(blkid -s "$PIDSel" -o value "$ROOT_PART")"
  echo "BOOT_PART= $BOOT_PART"
  echo "ROOT_PART= $ROOT_PART"
  echo "$PIDSel"_BOOT= "$BOOTID"
  echo "$PIDSel"_ROOT= "$ROOTID"
  lsblk -f
}

BootFormat () {
  bootlabel="EFI"
  rootlabel="ROOT"
  mkfs.fat -F32 -n "$bootlabel" "$BOOT_PART"
  #mlabel -i "$BOOT_PART" ::"$bootlabel"
}

RootFormat () {
  case "$FSSel" in
    Ext4Format)
    mkfs.ext4 "$ROOT_PART" -L "$rootlabel"
    #e2label "$ROOT_PART" "$rootlabel"
    mount "$ROOT_PART" /mnt
    FstabType='ext4'
    FstabOptions=''
    ;;
    BtrfsFormat)
    mkfs.btrfs -f -L "$rootlabel" "$ROOT_PART"
    btrfsdep="snapper btrfs-progs"
    btrfsgrub_pkg='grub-btrfs'
    modules="btrfs"
    mount "$ROOT_PART" /mnt
    SubVol=('' 'home' 'snapshots')
    for b in "${SubVol[@]}"; do
      btrfs su cr /mnt/@"$b"
    done
    umount /mnt
    mount -o noatime,compress=lzo,space_cache=v2,subvol=@ "$ROOT_PART" /mnt
    mkdir -p /mnt/{home,snapshots}
    mount -o noatime,compress=lzo,space_cache=v2,subvol=@home "$ROOT_PART" /mnt/home
    mount -o noatime,compress=lzo,space_cache=v2,discard=async,subvol=@snapshots "$ROOT_PART" /mnt/snapshots
    FstabType='btrfs'
    FstabOptions="rw,noatime,ssd,compress=lzo,space_cache=v2,subvol="
    for f in "${SubVol[@]}"; do
      echo -e "$PIDSel=$ROOTID /$f $FstabType $FstabOptions@$f 0 0" >> UNIfstab
    done
    ;;
    *)
    ;;
  esac
  mkdir /mnt/boot
  mount "$BOOT_PART" /mnt/boot
  lsblk -f
  echo -e "$PIDSel=$BOOTID /boot vfat rw,defaults 0 2" >> UNIfstab
}

ExternalDriveSetup () {
  case "$EXT_DRIVE" in
  "$DRIVE") echo 'ERROR you cannot use the same disk as for the primary, choose it right' 
            EXT_DRIVE="$(dialog --stdout --menu "Select EXTERNAL disk" 0 0 0 ${devicelist} || exit 1)"
            ExternalDriveSetup ;;
  '') echo 'No secondary drive to setup' ;;
  *) echo 'yes' 
  sudo ntfsfix /dev/sda1
  mkdir -p /mnt/media/{internal_hdd,USB}
  mount "$EXT_DRIVE" /mnt/media/internal_hdd;;
  esac
  #if [[ "$EXT_DRIVE" == "" ]]; then echo 'No secondary drive to setup'
}

BaseSystemInstall () {
  local BasePKG=( $linux $init $btrfsdep $elogind ) 
  "$pkgstrap" /mnt $microcode
  "$pkgstrap" /mnt "${BasePKG[@]}"
}

FstabGen () {
  rm /mnt/etc/fstab
  case "$OSSel" in
    1|Arch|arch|2|Artix|artix)
      case "$PIDSel" in
        UUID) "$fstabgen" -U /mnt >> /mnt/etc/fstab ;;
        PARTUUID) "$fstabgen" -t PARTUUID /mnt >> /mnt/etc/fstab ;;
        LABEL) "$fstabgen" -L /mnt >> /mnt/etc/fstab ;;
        *) "$fstabgen" -U /mnt >> /mnt/etc/fstab ;;
      esac
    ;;
    3|Void|void) cp UNIfstab /mnt/etc/fstab
    ;;
    *) echo "Wrong distro selected, try again" && OperatingSystemSel && FstabGen
    ;;
  esac
  cat /mnt/etc/fstab
}

SyncTime () {
  "$chroot" /mnt ln -sf /usr/share/zoneinfo/"$TZSel" /etc/localtime
  "$chroot" /mnt hwclock --systohc --utc
  #RcConf=("HARDWARECLOCK=$HARDWARECLOCK" "KEYMAP=$KEYMAP" "FONT=$FONT" "TTYS=$TTYS")
  #for rc in "${RcConf[@]}"; do
  #echo "$rc" >> /mnt/etc/rc.conf
  #done
}

LocaleGen () {
  sed -i "/$LocSel/ s/#//g" /mnt/etc/locale.gen
  "$chroot" /mnt locale-gen
  echo "LANG=$LangSel" >> /mnt/etc/locale.conf
  echo "$keylayout" >> /mnt/"$keypath"
  echo "$keylayout" >> /mnt/etc/vconsole.conf
}

HostConfig () {
  echo -e " $HNSel \n 127.0.0.1 localhost \n ::1 localhost \n 127.0.1.1 $HNSel.localdomain $HNSel" >> /mnt/etc/hosts
}

PackageConfig () {
  echo "$OSSel"
  case "$OSSel" in
    1|Arch|arch)
      "$chroot" /mnt pacman -Syu "${pkgskips[@]}"
      "$chroot" /mnt pacman-key --init
      "$chroot" /mnt pacman-key --populate archlinux
      sed -i '/\[multilib],/mirrorlist/ s/#//' /mnt/etc/pacman.conf
    ;;
    2|Artix|artix)
      "$chroot" /mnt pacman -Syu "${pkgskips[@]}" artix-archlinux-support
      "$chroot" /mnt pacman-key --populate archlinux
      RepoList=( '[extra]' 'Include = /etc/pacman.d/mirrorlist-arch'
                 '[community]' 'Include = /etc/pacman.d/mirrorlist-arch'
                 '[multilib]' 'Include = /etc/pacman.d/mirrorlist-arch')
      for p in "${RepoList[@]}"; do
        echo "$p" >> /mnt/etc/pacman.conf
      done
      #sed -i '/\[lib32]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf
    ;;
    3|Void|void)
      echo -e "nothing"
    ;;
    *)
      echo "Wrong distro selected, try again" && OperatingSystemSel && PackageConfig
    ;;
    esac
}

PackageInstall () {
  EssentialPKG=( $dev $fs $net $audio $filemanager $baseutils $media $rcpacks )
  AdditivePKG=( $vulkan $hardwareacceleration $nvidiagraphics $print $apps $bluetooth $android $archive )
  ExtraPKG=( $xorg $filemanager $media )
  if [ "$VBTSel" = 1 ]; then
  "$chroot" /mnt "$pkgmanager" -Syu "${pkgskips[@]}" "${EssentialPKG[@]}"
  else
  "$chroot" /mnt "$pkgmanager" -Syu "${pkgskips[@]}" "${EssentialPKG[@]}" "${AdditivePKG[@]}"
  fi
  #"$chroot" /mnt "$pkgmanager" -Syu 
  #cp ../UNI/Conf_files/mkinitcpio.conf /mnt/etc
  sed -i "/MODULES/ s/()/($modules)/" /mnt/etc/mkinitcpio.conf
}

ServiceEnabler () {
  #"$chroot" /mnt << EOF
  ServiceSel=('NetworkManager' 'cupsd' 'avahi-daemon')
  for c in  "${ServiceSel[@]}"; do
  "$chroot" /mnt "$initc0" "$initc1" "$c" "$initc2"
  done
  #keymaps
  #"$chroot" /mnt tlp start || true
}

AudioSetup () {
  ###echo "options snd-hda-intel model=auto" | sudo tee -a /mnt/etc/modprobe.d/alsa-base.conf
  ###echo "blacklist snd_soc_skl" | sudo tee -a /mnt/etc/modprobe.d/blacklist.conf
  ##echo "options snd-hda-intel dmic_detect=0" | sudo tee -a /mnt/etc/modprobe.d/alsa-base.conf
  echo "options snd-intel-dspcfg dsp_driver=1" >> /mnt/etc/modprobe.d/dsp.conf
  cp -r /mnt/usr/share/pipewire /mnt/etc/
}

UserSetup () {
  "$chroot" /mnt useradd -mG wheel,video,storage,input "$UNSel" #,lp,scanner,power
  sed -i '/%wheel ALL=(ALL) ALL/ s/# //' /mnt/etc/sudoers
  #sed -i 's/"us"/"it"/' /etc/conf.d/keymaps
  "$chroot" /mnt echo -n "Type password for $UNSel : "
  "$chroot" /mnt passwd "$UNSel"
  "$chroot" /mnt echo -n "Type password for root user : "
  "$chroot" /mnt passwd
}

BootloaderInstall () {
  echo "$BLSel"
  case $BLSel in
    1|REFIND|Refind|refind)
      "$chroot" /mnt "$pkgmanager" -Sy "${pkgskips[@]}" refind
      "$chroot" /mnt refind-install
      mkdir /mnt/boot/EFI/refind/themes
      mv /mnt/boot/EFI/refind/refind.conf /mnt/boot/EFI/refind/backup-refind.conf
      mv /mnt/boot/refind_linux.conf /mnt/boot/backup-refind_linux.conf
      cp ../UNI/Bootloader/Refind/refind.conf /mnt/boot/EFI/refind/refind.conf
      cp ../UNI/Bootloader/Refind/refind_linux.conf /mnt/boot/refind_linux.conf
      cp -r ../UNI/Bootloader/Refind/themes/* /mnt/boot/EFI/refind/themes/
      echo '!!!Refind config and theme changed!!!'
    ;;
    2|GRUB|Grub|grub)
      case "$UefiMode" in
        0)
        "$chroot" /mnt "$pkgmanager" -Sy "${pkgskips[@]}" grub "$btrfsgrub_pkg"
        "$chroot" /mnt grub-install --target=i386-pc --recheck --debug /boot
        ;;
        *) 
        "$chroot" /mnt "$pkgmanager" -Sy "${pkgskips[@]}" "$grub_pkg" $btrfsgrub_pkg
        "$chroot" /mnt grub-install --target=x86_64-efi --efi-directory=/boot bootloader-id=GRUB
        ;;
      esac  
      mkdir -p /mnt/boot/grub/themes
      sed -i '$ a\GRUB_THEME="/boot/grub/themes/Grub-Eiffel/theme.txt"' /mnt/etc/default/grub
      "$chroot" /mnt grub-mkconfig -o /boot/grub/grub.cfg
      cp -r ../UNI/Bootloader/Grub-Eiffel /mnt/boot/grub/themes/
    ;;
    3|EFISTUB|Efistub|efistub)
      BFlags="\'rw root=$PIDSel=$ROOTID rootflags=subvol=@ initrd=\intel-ucode.img initrd=\initramfs-linux.img\'"
      "$chroot" /mnt efibootmgr -c -d "$BOOT_PART" -p 1 -L "$OSSel" -l /vmlinuz-linux -u "$BFlags" --verbose
      echo "efibootmgr -b lastnumber -B" #delete previous boot entries
    ;;
    *)
      echo "Wrong bootloader selected, try another"
      BootLoaderSel
      BootloaderInstall
      echo "done"
    ;;
    esac
}

########## INSTALLATION-PROCESS ##########

YesNoSel () {
  read -rp "$1 $2 $3 [y/N] " YNS
  case "$YNS" in 
    [yY] | [yY][eE][sS]) CC=1 ;;
    [nN] | [nN][oO]) CC=0 ;;
    *) YesNoSel "$1" ;;
  esac
}

BaseInstallation () {
  CheckAS
  local SelectionSteps=( 'OperatingSystemSel' 'LocalizationSel' 'LanguageSel' 'TimezoneSel' 
  'HostnameSel' 'UsernameSel' 'PartIDSel' 'FilesystemSel' 'BootloaderSel' )
  
  local ArchTixSteps=( 'DiskPartition' 'BootFormat' 'RootFormat' 'ExternalDriveSetup' 
  'BaseSystemInstall' 'FstabGen' 'SyncTime' 'LocaleGen' 'HostConfig' 'PackageConfig' 'PackageInstall' 
  'ServiceEnabler' 'AudioSetup' 'UserSetup' 'BootloaderInstall' )
  
  local VoidSteps=( 'VoidInstMethod' 'DiskPartition' 'BootFormat' 'RootFormat' 'VoidPreChroot' 
                    'VoidInChroot' 'UserSetup' 'BootloaderInstall' )
  
  VirtualBoxTest
  if [ "$VBTSel" = 1 ]; then 
  SelectionSteps=('OperatingSystemSel')
  LangSel="en_GB.UTF-8" 
  LocSel="en_GB.UTF-8" 
  HNSel=tarch1 
  UNSel=tarch1 
  TZSel="Europe/Rome" 
  PIDSel="UUID" 
  FSSel=BtrfsFormat 
  BLSel="refind"
  fi
  
  for s in "${SelectionSteps[@]}"; do
  "$s"
  done
  
  case "$OSSel" in
    1|Arch|arch) 
    pkgmanager=pacman
    pkgskips=(--needed --noconfirm)
    keylayout='KEYMAP=it'
    keypath="etc/vconsole.conf"
    pkgstrap=pacstrap
    fstabgen=genfstab
    chroot='arch-chroot'
    initc0=systemctl
    initc1=enable
    initc2=""
    grub_pkg='grub'
    sed -i 's/lightdm-openrc//' ../UNI/full_setup
    sed -i 's/gdm-openrc//' ../UNI/full_setup
    for a in "${ArchTixSteps[@]}"; do "$a"
    done
    ;;
    2|Artix|artix)
    pkgmanager=pacman
    pkgskips=(--needed --noconfirm)
    keylayout='KEYMAP=it'
    keypath='etc/conf.d/keymaps'
    pkgstrap=basestrap
    fstabgen=fstabgen
    chroot='artix-chroot'
    init=openrc
    initc0='rc-update'
    initc1=add
    initc2=default
    rcpacks="$rc"
    elogind='elogind elogind-openrc'
    grub_pkg='grub'
    pacman-key --init
    pacman-key --populate artix
    pacman -Sy "${pkgskips[@]}" artix-archlinux-support #lib32-artix-archlinux-support
    for a in "${ArchTixSteps[@]}"; do "$a"
    done
    ;;
    3|Void|void) 
    pkgmanager="xbps-install"
    FSSel=Ext4Format
    BLSel='Grub'
    grub_pkg='grub-x86_64-efi'
    chroot='chroot'
    keylayout='KEYMAP=it'
    for a in "${VoidSteps[@]}"; do "$a"
    done
    "$chroot" /mnt xbps-reconfigure -fa
    ;;
    *) echo "Wrong choice, type again" && OperatingSystemSel
    ;;
  esac
  FinishInst
}

FinishInst () {
  echo "INSTALL COMPLETED"
  echo -e " A copy of the script will be placed in your user home directory"
  cp "$(pwd)"/Conf_files/bashrc /mnt/home/"$UNSel"/.bashrc
  cp -r "$(pwd)" /mnt/home/"$UNSel"/
  touch /mnt/home/"$UNSel"/.profile
  echo 'export MOZ_ENABLE_WAYLAND=1' >> /mnt/home/"$UNSel"/.profile
  YesNoSel "Reboot system"
  case "$CC" in
    1) umount -R /mnt && reboot ;;
    0) echo "OK" && exit 0 ;;
    *) echo "Wrong choice" && YesNoSel "Reboot system" ;;
  esac
}

########## PACKAGE ##########

microcode='intel-ucode'
linux='base base-devel linux linux-firmware'
init=''
dev='wget git ntp linux-headers'
baseutils='man bash-completion kitty vim nano'
fs='efibootmgr os-prober mtools parted dosfstools sbsigntools ntfs-3g gvfs-mtp fwupd'
net='networkmanager network-manager-applet'
audio='pipewire pipewire-pulse pipewire-alsa pipewire-jack lib32-pipewire lib32-pipewire-jack wireplumber' #void bluetooth = libspa-bluetooth'  #pulseaudio pulseaudio-bluetooth pavucontrol ##pulseaudio-alsa alsa-utils , for wine use (lib32-libpulse lib32-alsa-plugins)
android='android-tools android-udev'
bluetooth='bluez bluez-utils bluez-plugins'
print='cups cups-pdf system-config-printer avahi'
xorg='xorg-server xorg-xinit xorg-xinit light numlockx libinput xorg-xinput xss-lock'
apps='telegram-desktop firefox feh calc fd bpytop adriconf' #for netwotk bmon
nvidiagraphics='nvidia-prime nvidia nvidia-utils lib32-nvidia-utils nvidia-settings'
hardwareacceleration='libva-mesa-driver mesa-vdpau intel-media-driver'
vulkan='vulkan-icd-loader lib32-vulkan-icd-loader lib32-mesa vulkan-intel lib32-vulkan-intel vulkan-mesa-layers'
filemanager='xed vifm pcmanfm tumbler raw-thumbnailer'
archive='file-roller bzip2 cpio gzip lha xz lzop p7zip tar unrar zip unzip' # atool moved on Aur
media='celluloid mate-utils pantheon-screenshot simplescreenrecorder'
elogind=''
rc='ntp-openrc avahi-openrc cups-openrc bluez-openrc networkmanager-openrc'

BaseInstallation 
