#!/bin/bash
#media=(celluloid mate-utils pantheon-screenshot simplescreenrecorder)

if [ "$(id -u)" == 0 ]; then echo "Please don't run as root." >&2; exit 1; fi

Check_required_files () {
	local files=( additional_setup )
	for a in "${files[@]}"; do if [ ! -f "$(pwd)/$a" ]; then echo "Missing required file: $a" && local miss+=("$a"); fi
	done
	if [[ -v miss ]]; then echo 'Required file(s):' "${miss[@]}"; exit 1 ; else source additional_setup ; fi
}

Installation () {
	local Steps=( Snapper Trizen GNOME Environment DisplayManager WindowManager )
	T=0
	for i in "${Steps[@]}"; do
		YesNoSel "You want $i ?"
		case "$CC" in
		1) echo yes ;;
		0) echo "Skipping $i" && unset 'Steps[T]' ;;
		esac
		T=$((T+1))
	done
	for i in "${Steps[@]}"; do "$i"; done
}

Snapper () {
	sudo -- bash -c "
	umount /.snapshots/
	rm -rf /.snapshots
	snapper -c root create-config /
	btrfs su del /.snapshots
	mkdir /.snapshots
	chmod 750 /.snapshots
	
	sed -i '/\(TIMELINE_LIMIT_HOURLY\|TIMELINE_LIMIT_DAILY\|TIMELINE_LIMIT_WEEKLY\|TIMELINE_LIMIT_MONTHLY\|TIMELINE_LIMIT_YEARLY\)/ s/=\"[0-9]\"*$/=\"1\"/g' /etc/snapper/configs/root
	sed -i "/ALLOW_USERS=\"\"/ s/\"\"/\"ArchTixUser\"/" /etc/snapper/configs/root
	
	chmod a+rx /.snapshots
	chown :ArchTixUser /.snapshots
	mkdir /etc/pacman.d/hooks
	cp ~/UNI/Conf_files/50-bootbackup.hook /etc/pacman.d/hooks/50-bootbackup.hook
	pacman -S rsync --noconfirm
	pacman -S rsync-openrc --noconfirm
	rc-update add rsyncd
	rc-service rsyncd start
	"
	#sudo systemctl enable snapper-timeline.timer
	#sudo systemctl enable snapper-cleanup.timer
	#sudo systemctl enable grub-btrfs.path
}

Trizen () {
	git clone https://aur.archlinux.org/trizen.git /home/ArchTixUser/Trizen
	cd /home/ArchTixUser/Trizen || exit
	makepkg -si
	trizen -Syu heimdall-grimler-git
	#clapper phinger-cursors bibata-cursor-translucent steamtinkerlaunch betterlockscreen
}

GNOME () {
	#sudo pacman -Syu gnome-shell gnome-control-center gnome-firmware baobab gnome-system-monitor xdg-desktop-portal-gtk gnome-weather gnuchess gnome-chess gnome-calculator gnome-keyring gnome-software gnome-software-packagekit-plugin flatpak evince nautilus xdg-desktop-portal xdg-desktop-portal-gnome xdg-desktop-portal-wlr xdg-desktop-portal-gtk file-roller
	sudo pacman -Syu gnome gdm gdm-openrc gst-libav #gnome-extra
	trizen -Syu gnome-browser-connector
	mkdir -p ~/{.wallpapers,.config/kitty,.config/autostart,/etc/xdg/autostart}
	cp -r /run/ArchTixUser/media/HDD/Pictures/* ~/.wallpapers
	cp ~/UNI/Conf_files/kitty.conf ~/.config/kitty/kitty.conf
	cp ~/UNI/Conf_files/Script/pfetch ~/.pfetch
	cp ~/UNI/Conf_files/nanorc ~/.nanorc
	echo 'Xft.dpi: 90' > ~/.Xdefaults
	chmod +x ~/.pfetch
	#cp -r /usr/share/pipewire /home/ArchTixUser/.config
	#sed -i 's/#{ path = "\/usr\/bin\/pipewire-media-session" args = ""/{ path = wireplumber args = "" }/' /home/ArchTixUser/.config/pipewire/pipewire.conf
	#sed -i '/#{ path = "\/usr\/bin\/pipewire" args = "-c pipewire-pulse.conf"/{ path = "\/usr\/bin\/pipewire" args = "-c pipewire-pulse.conf" }/' /home/ArchTixUser/.config/pipewire/pipewire.conf
	#cp -r ~/UNI/Conf_files/Pipewire/* ~/.config/autostart 
	#sudo cp -r ~/UNI/Conf_files/Pipewire/* /etc/xdg/autostart/
	sudo rc-update add gdm default
	sudo systemctl enable gdm
	echo "MOZ_ENABLE_WAYLAND=1" | sudo tee -a /etc/environment > /dev/null
}

Environment () {
	#cp -r /mnt/usr/share/pipewire /mnt/home/ArchTixUser/.config
	#sed 's/#{ path = "/usr/bin/pipewire-media-session" args = "" }/{ path = "wireplumber"  args = "" }/' /mnt/home/ArchTixUser/.config
	#sed '/#{ path = "/usr/bin/pipewire" args = "-c pipewire-pulse.conf" }/ s/#//' /mnt/home/ArchTixUser/.config/pipewire/pipewire.conf

	sudo pacman -S ttf-roboto rofi sxiv feh python-pywal lxappearance kalgebra imagemagick pacman-contrib slock dunst tcl tk --noconfirm
	mkdir -p ~/{.wallpapers,.config/{kitty,polybar,rofi,dunst}}
	sudo ntpd -qg
	echo "Time set"

	echo '###################-PIPEWIRE-###################'
  	echo 'if not working --> cp -r /usr/share/pipewire /etc/'
  	#mkdir ~/.config/autostart
  	#cp -r ~/UNI/Conf_files/pipewire/ ~/.config/autostart
  	
	echo '###################-COPYING-###################'
	
	DD=0
	Folders=( '/media/internal_hdd/OS/Wallpapers/*' "$HOME/UNI/Conf_files/picom.conf" "$HOME/UNI/Conf_files/Dunst/*" "$HOME/UNI/Conf_files/Script/toggle-touchpad.sh" "$HOME/UNI/Conf_files/Script/low-battery.sh"
		"$HOME/UNI/Conf_files/config.rasi" "$HOME/UNI/Conf_files/kitty.conf" "$HOME/UNI/Conf_files/Script/pfetch" "$HOME/UNI/Conf_files/nanorc" '/etc/X11/xinit/xinitrc' )
	Destinations=( "$HOME/.wallpapers" "$HOME/.config/picom.conf" "$HOME/.config/dunst/" "$HOME/.config/toggle-touchpad.sh" "$HOME/.config/low-battery.sh"
		"$HOME/.config/rofi/config.rasi" "$HOME/.config/kitty/kitty.conf" "$HOME/.pfetch" "$HOME/.nanorc" "$HOME/.xinitrc" )
	for a in "${Folders[@]}"; do cp a "${Destinations[DD]}" ; DD="$(DD+1)" ; done
	echo 'Xft.dpi: 90' | tee -a ~/.Xdefaults > /dev/null
	echo "light -S 30" | sudo tee -a ~/.xprofile > /dev/null
	sudo cp ~/UNI/Conf_files/40-libinput.conf /usr/share/X11/xorg.conf.d/40-libinput.conf
	sudo ln -s /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
	sudo cp ~/UNI/Conf_files/90-backlight.rules /usr/lib/udev/rules.d/90-backlight.rules
	
	echo '###################-PERMISSIONS-###################'
	
	chmod +x ~/.xinitrc ~/.config/toggle-touchpad.sh ~/.config/dunst/dunst-color.sh ~/.config/low-battery.sh ~/.pfetch
}

DisplayManager () {
	sudo -- bash -c "
	pacman -Sy lightdm lightdm-openrc lightdm-webkit2-greeter lightdm-webkit-theme-litarvan
	sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-webkit2-greeter/' /etc/lightdm/lightdm.conf
	sed -i 's/antergos/litarvan/g' /etc/lightdm/lightdm-webkit2-greeter.conf
	rc-update add lightdm default
	systemctl enable lightdm
	"
}

function WindowManager () {
	read -rp "What setup you want? [bspwm herbstluftwm hyprland xmonad polybar] " SS
	case $SS in
	bspwm ) sudo pacman -S bspwm sxhkd --noconfirm
		mkdir ~/.config/{bspwm,sxhkd}
		cp ~/UNI/Conf_files/Bspwm/sxhkdrc ~/.config/sxhkd/sxhkdrc
		cp ~/UNI/Conf_files/Bspwm/bspwmrc ~/.config/bspwm/bspwmrc
		chmod +x ~/.config/sxhkd/sxhkdrc ~/.config/bspwm/bspwmrc
	;;
	herbstluftwm ) sudo pacman -S herbstluftwm --noconfirm
		mkdir ~/.config/herbstluftwm
		cp ~/UNI/Conf_files/Herbstluftwm/autostart ~/.config/herbstluftwm/
		chmod +x ~/.config/herbstluftwm/autostart
	;;
	hyprland ) sudo pacman -S hyprland hyprcursor hyprgraphics hyprland hyprland-qtutils hyprland-qt-support hyprlock hyprutils hyprwayland-scanner  --noconfirm
		mkdir ~/.config/hyprland
		cp ~/UNI/Conf_files/hyprland/hyprland.conf ~/.config/hyprland/hyprland.conf
		SYMLINK_NAME="igpu"
		RULE_PATH="/etc/udev/rules.d/igpu-dev-path.rules"
		IGPU_ID=$(lspci -d ::03xx | grep 'Intel' | cut -f1 -d' ')
		UDEV_RULE="KERNEL="="card*"", KERNELS="="0000:$IGPU_ID"", SUBSYSTEM="="drm"", SUBSYSTEMS="="pci"", SYMLINK+"="dri/$SYMLINK_NAME"""
		echo "$UDEV_RULE" | sudo tee "$RULE_PATH"
		sudo udevadm control --reload
		sudo udevadm trigger
	;;
	xmonad )  sudo pacman -S xmonad xmonad-contrib xmobar --noconfirm
		mkdir ~/.xmonad
		cp ~/UNI/Conf_files/Xmonad/xmonad.hs ~/.xmonad/xmonad.hs
		cp ~/UNI/Conf_files/Xmonad/xmobarrc ~/.xmobarrc
	;;
	polybar ) sudo pacman -S xdotool xorg-xwininfo xorg-xev  --noconfirm
		trizen -S polybar
		mkdir ~/.config/polybar
		cp ~/UNI/Conf_files/Polybar/* ~/.config/polybar/
		chmod +x ~/.config/polybar/launch.sh ~/.config/polybar/hide
	;;
	*) echo "Wrong choice, type again" && WindowManager
	;;
	esac
	
	YesNoSel "Want another WindowManager?"
	if [ "$CC" = 1 ]; then WindowManager ; else echo 'Finished installation' ; fi
}
Check_required_files
Installation
