#!/bin/bash
#media=(celluloid mate-utils pantheon-screenshot simplescreenrecorder)

Check_required_files () {
	local files=( additional_setup )
	for a in "${files[@]}"; do if [ ! -f "$(pwd)/$a" ]; then echo "Missing required file: $a" && local miss+=("$a"); fi
	done
	if [[ -v miss ]]; then echo 'Required file(s):' "${miss[@]}"
	else source additional_setup ; fi
}

Installation () {
	local Steps=( 'Snapper' 'Trizen' GNOME 'Environment' 'DisplayManager' 'WindowManager' )
	T=0
	for i in "${Steps[@]}"; do
		YesNoSel "You want $i ?"
		case "$CC" in
		1) echo yes ;;
		0) echo "Skipping $i" && unset 'Steps[T]' ;;
		*) echo 'Wrong choice' && Installation ;;
		esac
		T=$((T+1))
	done
	for i in "${Steps[@]}"; do "$i"; done
}

Snapper () {
	sudo -- bash -c "
	umount /.snapshots/
	rm -rf /.snapshots
	snapper -c root create-config /
	btrfs su del /.snapshots
	mkdir /.snapshots
	chmod 750 /.snapshots
	
	sed -i '/\(TIMELINE_LIMIT_HOURLY\|TIMELINE_LIMIT_DAILY\|TIMELINE_LIMIT_WEEKLY\|TIMELINE_LIMIT_MONTHLY\|TIMELINE_LIMIT_YEARLY\)/ s/=\"[0-9]\"*$/=\"1\"/g' /etc/snapper/configs/root
	sed -i '/ALLOW_USERS=\"\"/ALLOW_USERS=\"tarch1\"/' /etc/snapper/configs/root
	
	chmod a+rx /.snapshots
	chown :tarch1 /.snapshots
	mkdir /etc/pacman.d/hooks
	cp ~/UNI/Conf_files/50-bootbackup.hook /etc/pacman.d/hooks/50-bootbackup.hook
	pacman -S rsync --noconfirm
	"
	#sudo systemctl enable snapper-timeline.timer
	#sudo systemctl enable snapper-cleanup.timer
	#sudo systemctl enable grub-btrfs.path
}

Trizen () {
  git clone https://aur.archlinux.org/trizen.git /home/tarch1/Trizen
  cd /home/tarch1/Trizen || exit
  makepkg -si
  #clapper phinger-cursors bibata-cursor-translucent steamtinkerlaunch betterlockscreen
}

GNOME () {
	#sudo pacman -Syu gnome-shell gnome-control-center gnome-firmware baobab gnome-system-monitor xdg-desktop-portal-gtk gnome-weather gnuchess gnome-chess gnome-calculator gnome-keyring gnome-software gnome-software-packagekit-plugin flatpak evince nautilus xdg-desktop-portal xdg-desktop-portal-gnome xdg-desktop-portal-wlr xdg-desktop-portal-gtk file-roller
	sudo pacman -Syu gnome gdm gdm-openrc gst-libav #gnome-extra
	trizen -Syu gnome-browser-connector
	mkdir -p ~/{.wallpapers,.config/kitty}
	cp -r /run/tarch1/media/HDD/Pictures/* ~/.wallpapers
	cp ~/UNI/Conf_files/kitty.conf ~/.config/kitty/kitty.conf
	cp ~/UNI/Conf_files/Script/pfetch ~/.pfetch
	cp ~/UNI/Conf_files/nanorc ~/.nanorc
	echo 'Xft.dpi: 90' > ~/.Xdefaults
	chmod +x ~/.pfetch
	#sudo mkdir -p /etc/xdg/autostart/
	cp -r /mnt/usr/share/pipewire /mnt/home/"$UNsel"/.config
	sed 's/#{ path = "/usr/bin/pipewire-media-session" args = "" }/{ path = "wireplumber"  args = "" }/' /mnt/home/"$UNsel"/.config
	sed '/#{ path = "/usr/bin/pipewire" args = "-c pipewire-pulse.conf" }/ s/#//' /mnt/home/"$UNsel"/.config/pipewire/pipewire.conf
	mkdir ~/.config/autostart
	cp -r ~/UNI/Conf_files/pipewire/ ~/.config/autostart
	sudo rc-update add gdm default
	sudo systemctl enable gdm
	echo "MOZ_ENABLE_WAYLAND=1" | sudo tee -a /etc/environment > /dev/null
}

Environment () {
	cp -r /mnt/usr/share/pipewire /mnt/home/"$UNsel"/.config
	sed 's/#{ path = "/usr/bin/pipewire-media-session" args = "" }/{ path = "wireplumber"  args = "" }/' /mnt/home/"$UNsel"/.config
	sed '/#{ path = "/usr/bin/pipewire" args = "-c pipewire-pulse.conf" }/ s/#//' /mnt/home/"$UNsel"/.config/pipewire/pipewire.conf

  sudo pacman -S ttf-roboto rofi sxiv feh python-pywal lxappearance kalgebra imagemagick pacman-contrib slock dunst tcl tk --noconfirm
  mkdir -p ~/{.wallpapers,.config/{kitty,polybar,rofi,dunst}}
  
  sudo ntpd -qg
  echo "Time set"
  
  ###################-PIPEWIRE-###################
  
  cp -r /usr/share/pipewire /etc/
  # mkdir ~/.config/autostart
  # cp -r ~/UNI/Conf_files/pipewire/ ~/.config/autostart
  
  ###################-COPYING-###################
  
  cp -r /media/internal_hdd/OS/Wallpapers/* ~/.wallpapers
  cp ~/UNI/Conf_files/picom.conf ~/.config/picom.conf
  cp ~/UNI/Conf_files/Dunst/* ~/.config/dunst/ 
  cp ~/UNI/Conf_files/Script/toggle-touchpad.sh ~/.config/toggle-touchpad.sh
  cp ~/UNI/Conf_files/Script/low-battery.sh ~/.config/low-battery.sh
  cp ~/UNI/Conf_files/config.rasi ~/.config/rofi/config.rasi
  cp ~/UNI/Conf_files/kitty.conf ~/.config/kitty/kitty.conf
  cp ~/UNI/Conf_files/Script/pfetch ~/.pfetch
  cp ~/UNI/Conf_files/nanorc ~/.nanorc
  cp /etc/X11/xinit/xinitrc ~/.xinitrc
  echo 'Xft.dpi: 90' | tee -a ~/.Xdefaults > /dev/null
  echo "light -S 30" | sudo tee -a ~/.xprofile > /dev/null
  sudo cp ~/UNI/Conf_files/40-libinput.conf /usr/share/X11/xorg.conf.d/40-libinput.conf
  sudo ln -s /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
  sudo cp ~/UNI/Conf_files/90-backlight.rules /usr/lib/udev/rules.d/90-backlight.rules
  
  ###################-PERMISSIONS-###################
  
  chmod +x ~/.xinitrc ~/.config/toggle-touchpad.sh ~/.config/dunst/dunst-color.sh ~/.config/low-battery.sh ~/.pfetch
}

DisplayManager () {
  sudo -- bash -c "
  pacman -Sy lightdm lightdm-openrc lightdm-webkit2-greeter lightdm-webkit-theme-litarvan
  sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-webkit2-greeter/' /etc/lightdm/lightdm.conf
  sed -i 's/antergos/litarvan/g' /etc/lightdm/lightdm-webkit2-greeter.conf
  rc-update add lightdm default
  systemctl enable lightdm
  "
}

function WindowManager () {
  read -rp "What setup you want? [bspwm herbstluftwm xmonad polybar] " SS
  case $SS in
    bspwm ) sudo pacman -S bspwm sxhkd --noconfirm
            mkdir ~/.config/{bspwm,sxhkd}
            cp ~/UNI/Conf_files/Bspwm/sxhkdrc ~/.config/sxhkd/sxhkdrc
            cp ~/UNI/Conf_files/Bspwm/bspwmrc ~/.config/bspwm/bspwmrc
            chmod +x ~/.config/sxhkd/sxhkdrc ~/.config/bspwm/bspwmrc
    ;;
    herbstluftwm ) sudo pacman -S herbstluftwm --noconfirm
                   mkdir ~/.config/herbstluftwm
                   cp ~/UNI/Conf_files/Herbstluftwm/autostart ~/.config/herbstluftwm/
                   chmod +x ~/.config/herbstluftwm/autostart
    ;;
    xmonad )  sudo pacman -S xmonad xmonad-contrib xmobar --noconfirm
              mkdir ~/.xmonad
              cp ~/UNI/Conf_files/Xmonad/xmonad.hs ~/.xmonad/xmonad.hs
              cp ~/UNI/Conf_files/Xmonad/xmobarrc ~/.xmobarrc
    ;;
    polybar ) sudo pacman -S xdotool xorg-xwininfo xorg-xev  --noconfirm
              trizen -S polybar
              mkdir ~/.config/polybar
              cp ~/UNI/Conf_files/Polybar/* ~/.config/polybar/
              chmod +x ~/.config/polybar/launch.sh ~/.config/polybar/hide
    ;;
    *) echo "Wrong choice, type again" && WindowManager
    ;;
  esac

  YesNoSel "Want another WindowManager?"
  if [ "$CC" = 1 ]; then WindowManager ; else echo 'Finished installation' ; fi
}
Check_required_files
Installation
