#!/bin/bash
Part=( 'Snapper' 'Trizen' 'Environment' 'DisplayManager' 'WindowManager' )
Installation () {
  for i in "${Part[@]}"; do
  YesNoSel "You need" "$i" "?"
  done
  if [ "$Snapper" = 1 ]; then
  Snapper
  fi
  if [ "$Trizen" = 1 ]; then
  Trizen
  fi
  if [ "$Environment" = 1 ]; then
  Environment
  fi
  if [ "$DisplayManager" = 1 ]; then
  DisplayManager
  fi
  if [ "$WindowManager" = 1 ]; then
  WindowManager
  fi
}

Snapper () {
  sudo umount /.snapshots/
  sudo rm -rf /.snapshots
  sudo snapper -c root create-config /
  sudo btrfs su del /.snapshots
  sudo mkdir /.snapshots
  sudo chmod 750 /.snapshots
  
  sudo sed -i 's/ALLOW_USERS=""/ALLOW_USERS="tarch1"/g' /etc/snapper/configs/root
  sudo sed -i 's/TIMELINE_LIMIT_HOURLY="10"/TIMELINE_LIMIT_HOURLY="3"/g' /etc/snapper/configs/root
  sudo sed -i 's/TIMELINE_LIMIT_DAILY="10"/TIMELINE_LIMIT_DAILY="2"/g' /etc/snapper/configs/root
  sudo sed -i 's/TIMELINE_LIMIT_WEEKLY="0"/TIMELINE_LIMIT_WEEKLY="1"/g' /etc/snapper/configs/root
  sudo sed -i 's/TIMELINE_LIMIT_MONTHLY="10"/TIMELINE_LIMIT_MONTHLY="1"/g' /etc/snapper/configs/root
  sudo sed -i 's/TIMELINE_LIMIT_YEARLY="10"/TIMELINE_LIMIT_YEARLY="1"/g' /etc/snapper/configs/root
  
  sudo chmod a+rx /.snapshots
  sudo chown :tarch1 /.snapshots
  sudo mkdir /etc/pacman.d/hooks
  sudo cp ~/UNI/Conf_files/50-bootbackup.hook /etc/pacman.d/hooks/50-bootbackup.hook
  sudo pacman -S rsync --noconfirm
  
#sudo systemctl enable snapper-timeline.timer
#sudo systemctl enable snapper-cleanup.timer
#sudo systemctl enable grub-btrfs.path

#rc-update add snapper-timeline.timer default
#rc-update add snapper-cleanup.timer default
#rc-update add grub-btrfs.path default
}

Trizen () {
  git clone https://aur.archlinux.org/trizen.git ~/trizen
  cd ~/trizen || Trizen
  makepkg -si
  trizen -S clapper bibata-cursor-translucent
  #picom-ibhagwan-git gllock-git xidlehook wpgtk-git font-manager ttf-font-awesome betterlockscreen bibata-rainbow-cursor-theme
}

Environment () {
  sudo pacman -S ttf-roboto rofi sxiv feh python-pywal lxappearance imagemagick pacman-contrib slock dunst tcl tk --noconfirm
  mkdir -p ~/{.wallpapers,.config/{kitty,polybar,rofi,dunst}}
  
  sudo ntpd -qg
  echo "Time set"
  
  ###################-PIPEWIRE-###################
  
  cp -r /usr/share/pipewire /etc/
  # mkdir ~/.config/autostart
  # cp -r ~/UNI/Conf_files/pipewire/ ~/.config/autostart
  
  ###################-COPYING-###################
  
  cp -r /media/internal_hdd/OS/Wallpapers/* ~/.wallpapers
  cp ~/UNI/Conf_files/picom.conf ~/.config/picom.conf
  cp ~/UNI/Conf_files/Dunst/dunstrc ~/.config/dunst/dunstrc
  cp ~/UNI/Conf_files/Dunst/dunst-color.sh ~/.config/dunst/dunst-color.sh 
  cp ~/UNI/Conf_files/Script/toggle-touchpad.sh ~/.config/toggle-touchpad.sh
  cp ~/UNI/Conf_files/Script/low-battery.sh ~/.config/low-battery.sh
  cp ~/UNI/Conf_files/config.rasi ~/.config/rofi/config.rasi
  cp ~/UNI/Conf_files/kitty.conf ~/.config/kitty/kitty.conf
  cp ~/UNI/Conf_files/Script/pfetch ~/.pfetch
  cp ~/UNI/Conf_files/nanorc ~/.nanorc
  cp /etc/X11/xinit/xinitrc ~/.xinitrc
  echo 'Xft.dpi: 90' | tee -a ~/.Xdefaults > /dev/null
  echo "light -S 30" | sudo tee -a ~/.xprofile > /dev/null
  sudo cp ~/UNI/Conf_files/40-libinput.conf /usr/share/X11/xorg.conf.d/40-libinput.conf
  sudo ln -s /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
  sudo cp ~/UNI/Conf_files/90-backlight.rules /usr/lib/udev/rules.d/90-backlight.rules
  
  ###################-PERMISSIONS-###################
  
  chmod +x ~/.xinitrc
  chmod +x ~/.config/toggle-touchpad.sh
  chmod +x ~/.config/dunst/dunst-color.sh
  chmod +x ~/.config/low-battery.sh
  chmod +x ~/.pfetch
  
  ###################-EXECUTION-###################
  
  sudo sed -i '/ntfs/ s/ro/rw/' /etc/fstab
  sudo ntfsfix /dev/sda1
  #wpg-install.sh -b -g -i
}

DisplayManager () {
  sudo pacman -Sy lightdm lightdm-openrc lightdm-webkit2-greeter lightdm-webkit-theme-litarvan
  sudo sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-webkit2-greeter/' /etc/lightdm/lightdm.conf
  sudo sed -i 's/antergos/litarvan/g' /etc/lightdm/lightdm-webkit2-greeter.conf
  sudo rc-update add lightdm default
  sudo systemctl enable lightdm
}
function WindowManager () {
  read -rp "What setup you want? [bspwm gnome herbstluftwm xmonad polybar]" SS
  case $SS in
bspwm ) sudo pacman -S bspwm sxhkd --noconfirm
mkdir ~/.config/{bspwm,sxhkd}
cp ~/UNI/Conf_files/Bspwm/sxhkdrc ~/.config/sxhkd/sxhkdrc
cp ~/UNI/Conf_files/Bspwm/bspwmrc ~/.config/bspwm/bspwmrc
chmod +x ~/.config/sxhkd/sxhkdrc
chmod +x ~/.config/bspwm/bspwmrc
;;
gnome ) sudo pacman -Syu lxappearance xdg-desktop-portal-gtk gnome
#gnome-shell gnome-control-center xdg-desktop-portal-gtk gnome-weather gnuchess gnome-chess gnome-calculator gnome-keyring evince
sudo pacman -Syu gdm gdm-openrc
trizen -Syu chrome-gnome-shell
mkdir -p ~/{.wallpapers,.config/{kitty}}
cp -r /media/internal_hdd/OS/Wallpapers/* ~/.wallpapers
cp ~/UNI/Conf_files/kitty.conf ~/.config/kitty/kitty.conf
cp ~/UNI/Conf_files/Script/pfetch ~/.pfetch
cp ~/UNI/Conf_files/nanorc ~/.nanorc
echo 'Xft.dpi: 90' > ~/.Xdefaults
#sudo cp ~/UNI/Conf_files/40-libinput.conf /usr/share/X11/xorg.conf.d/40-libinput.conf
#sudo ln -s /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
chmod +x ~/.pfetch
sudo mkdir -p /etc/xdg/autostart/
cp -r /usr/share/pipewire /etc/
#mkdir ~/.config/autostart
#cp -r ~/UNI/Conf_files/pipewire/ ~/.config/autostart
sudo rc-update add gdm default
sudo systemctl enable gdm
echo "MOZ_ENABLE_WAYLAND=1" | sudo tee -a /etc/environment > /dev/null
;;
herbstluftwm ) sudo pacman -S herbstluftwm --noconfirm
mkdir ~/.config/herbstluftwm
cp ~/UNI/Conf_files/Herbstluftwm/autostart ~/.config/herbstluftwm/
chmod +x ~/.config/herbstluftwm/autostart
;;
xmonad ) sudo pacman -S xmonad xmonad-contrib xmobar --noconfirm
mkdir ~/.xmonad
cp ~/UNI/Conf_files/Xmonad/xmonad.hs ~/.xmonad/xmonad.hs
cp ~/UNI/Conf_files/Xmonad/xmobarrc ~/.xmobarrc
;;
polybar ) sudo pacman -S xdotool xorg-xwininfo xorg-xev  --noconfirm
trizen -S polybar
mkdir ~/.config/polybar
cp ~/UNI/Conf_files/Polybar/hide ~/.config/polybar/hide
cp ~/UNI/Conf_files/Polybar/launch.sh ~/.config/polybar/launch.sh
cp ~/UNI/Conf_files/Polybar/config ~/.config/polybar/config
chmod +x ~/.config/polybar/launch.sh
chmod +x ~/.config/polybar/hide
;;
*) YesNoSel "Want another WindowManager?"
if [ "$CC" = 1 ]
then WindowManager
else echo "Nothing"
fi
;;
esac
}

YesNoSel () {
  read -rp "$1 $2 $3 [y/N]" YNS
  case "$YNS" in 
  [yY] | [yY][eE][sS] ) eval "$i=1"
  CC=1
  ;;
  [nN] | [nN][oO] ) eval "$i=0"
  ;;
  *) YesNoSel "$i" "$1"
  ;;
  esac
}

Installation
