#!/bin/bash

y=(pkg_microcode pkg_base pkg_ext pkg_init pkg_dev pkg_baseutils
   pkg_fs pkg_net pkg_audio pkg_android pkg_bluetooth pkg_print 
   pkg_xorg pkg_apps pkg_nvidiagraphics pkg_hardwareacceleration
   pkg_filemanager pkg_archive pkg_media pkg_elogind pkg_rc)

missing=()
# Defaults
pkg_microcode=(intel-ucode)
pkg_base=(base base-devel linux linux-firmware)
pkg_ext=(vulkan-icd-loader lib32-vulkan-icd-loader lib32-mesa vulkan-intel lib32-vulkan-intel vulkan-mesa-layers)
pkg_init=()
pkg_dev=(wget git ntp linux-headers)
pkg_baseutils=(man bash-completion kitty vim nano)
pkg_fs=(efibootmgr os-prober mtools parted dosfstools sbsigntools ntfs-3g gvfs-mtp)
pkg_net=(networkmanager network-manager-applet)
pkg_audio=(pipewire pipewire-pulse pipewire-alsa pipewire-jack lib32-pipewire lib32-pipewire-jack)
pkg_android=(android-tools android-udev)
pkg_bluetooth=(bluez bluez-utils bluez-plugins)
pkg_print=(cups cups-pdf system-config-printer avahi)
pkg_xorg=(xorg-server xorg-xinit xorg-xinit light numlockx libinput xorg-xinput xss-lock)
pkg_apps=(telegram-desktop firefox feh calc fd bpytop adriconf)
pkg_nvidiagraphics=(nvidia-prime nvidia nvidia-utils lib32-nvidia-utils nvidia-settings)
pkg_hardwareacceleration=(libva-mesa-driver mesa-vdpau intel-media-drive)
pkg_filemanager=(xed vifm pcmanfm tumbler raw-thumbnailer)
pkg_archive=(file-roller atool bzip2 cpio gzip lha xz lzop p7zip tar unrar zip unzip)
pkg_media=(celluloid mate-utils pantheon-screenshot simplescreenrecorder)
pkg_elogind=()
pkg_rc=(ntp-openrc avahi-openrc cups-openrc bluez-openrc networkmanager-openrc)

sudo pacman -Slq system world galaxy extra community multilib | sort > pacman_db

start () {
for c in "${y[@]}"; do
  var=("$c"[@])
  var1=("${!var}")
  testing "${var1[@]}"
  unset "$c"
  export "$c"="${test[*]}"
done
}

testing () {
for i in "${var1[@]}"; do
  if ! sudo pacman -Qs "${i}" 1>/dev/null; then
    echo "[x] Package not available: $i"
    missing+=("$i")
    array_t="${var1[*]}"
    test="${array_t//$i/}"
    unset array_t
    else
    test="${var1[*]}"
  fi
done
}

start
echo 'Present (---) MISSING (xxx)'
echo -e '<<<' "${missing[@]}" '>>>'
for i in "${y[@]}"; do
  ii=("${!i}")
  echo '---' "[[${i[*]}]]" "${ii[@]}"
done
