#!/bin/bash

x=(microcode base ext init dev baseutils fs net audio android bluetooth print xorg apps nvidiagraphics hardwareacceleration filemanager archive media elogind rc)

# Defaults
pkg_microcode=(intel-ucode)
pkg_base=(base base-devel linux linux-firmware)
pkg_ext=(vulkan-icd-loader lib32-vulkan-icd-loader lib32-mesa vulkan-intel lib32-vulkan-intel vulkan-mesa-layers)
pkg_init=()
pkg_dev=(wget git ntp linux-headers)
pkg_baseutils=(man bash-completion kitty vim nano)
pkg_fs=(efibootmgr os-prober mtools parted dosfstools sbsigntools ntfs-3g gvfs-mtp)
pkg_net=(networkmanager network-manager-applet)
pkg_audio=(pipewire pipewire-pulse pipewire-alsa pipewire-jack lib32-pipewire lib32-pipewire-jack)
pkg_android=(android-tools android-udev)
pkg_bluetooth=(bluez bluez-utils bluez-plugins)
pkg_print=(cups cups-pdf system-config-printer avahi)
pkg_xorg=(xorg-server xorg-xinit xorg-xinit light numlockx libinput xorg-xinput xss-lock)
pkg_apps=(telegram-desktop firefox feh calc fd bpytop adriconf '
pkg_nvidiagraphics='nvidia-prime nvidia nvidia-utils lib32-nvidia-utils nvidia-settings)
pkg_hardwareacceleration=(libva-mesa-driver mesa-vdpau intel-media-drive)
pkg_filemanager=(xed vifm pcmanfm tumbler raw-thumbnailer)
pkg_archive=(file-roller atool bzip2 cpio gzip lha xz lzop p7zip tar unrar zip unzip)
pkg_media=(celluloid mate-utils pantheon-screenshot simplescreenrecorder)
pkg_elogind=()
pkg_rc=(ntp-openrc avahi-openrc cups-openrc bluez-openrc networkmanager-openrc)
sudo pacman -Slq system world galaxy extra community multilib | sort > pacman_db

start () {
for c in "${x[@]}"; do
  y=$c
  var=(pkg_"$y"[@])
  testing "${var[@]}"
  #gggg="${!test}"
  unset pkg_"$c"
  export pkg_"$c"="${test[*]}"
  echo "GG=" "${pkg_microcode[@]}"
done
}

testing () {
var1=("${!var}")
for i in "${var1[@]}"; do
echo $i
  if ! sudo pacman -Qs "${i}" 1>/dev/null; then
    echo "[x] Package not available: $i"
    array_t="${var1[*]}"
    test="${array_t//$i/}"
    unset array_t
  fi
done
}

start
echo "${pkg_microcode[@]}" "${pkg_base[@]}"
