#!/bin/bash
#add zenith support
#add suspension https://forum.artixlinux.org/index.php/topic,1195.msg8554.html#msg8554
main() {
    # If there is argument, the assigned cases will be executed.
    while [[ $# -gt 0 ]] && [[ $1 == "--"* ]];
    do
        option=$1;
        shift;
        case $option in
        	"arch"*) echo test ;;
            "--version")
                whiptail --title "cfetch" --msgbox "cfetch version 0.1.3" 10 50;;
            "--help") usage;;
            *) fetch;;
        esac
    done

    # If the argument does not match on the cases, then system information will
    # be displayed.
    if [[ $option != "--"* ]]; then
        fetch
    fi
}
main "$@"

SelSteps () {
  OSSelection=( '4' 'Enter the distro we are going to setup : 1) Arch 2) Artix 3) Void \n'
                'OSSel' '2'
                '1|Arch|arch' 'distro selected : Arch' 'Arch'
                '2|Artix|artix' 'distro selected : Artix' 'Artix'
                '3|Void|void' 'distro selected : Void' 'Void'
                'echo "Wrong choice, type again" && OperatingSystemSel' )
  LocalizationSel=( '3' 'Select your locale zone' 'gg' )
  
  SelS=( 'OSSelection[@]' 'LocalizationSel[@]' ) 
  #'LanguageSel' 'TimezoneSel' 'HostnameSel' 'UsernameSel' 'PartIDSel' 'FilesystemSel' 'BootloaderSel' )
  for i in "${SelS[@]}"; do
    var=("${!i}")
    echo -en "${var[1]}"
    read -r "${var[2]}"
    ext=("${!var[2]}")
    ext2=("${!var[4]}")
    #YesNoSel "${var[3]}"
    case "${var[3]}" in
      1) echo "we are here" ;;
      2) case "${ext[@]}" in
           "${ext2[@]}") echo "${var[5]}" && eval "${var[2]}"="${var[6]}" ;;
           *) echo "${var[6]}" ;;
         esac ;;
      3) case "${ext[@]}" in
           "${var[4]}") echo "${var[5]}" && eval "${var[2]}"="${var[6]}" ;;
           "${var[7]}") echo "${var[8]}" && eval "${var[2]}"="${var[9]}" ;;
           *) echo "${var[10]}" ;;
         esac ;;
      4) case "${ext[@]}" in
           "${var[4]}") echo "${var[5]}" && eval "${var[2]}"="${var[6]}" ;;
           "${var[7]}") echo "${var[8]}" && eval "${var[2]}"="${var[9]}" ;;
           "${var[10]}") echo "${var[11]}" && eval "${var[2]}"="${var[12]}" ;;
           *) echo "${var[13]}" ;;
         esac ;;
      *) ;;
    esac
    echo 'done' "${var[2]} << = ${ext[*]}"
  done
}
SelSteps
