if [ "$(id -u)" -ne 0 ]; then
	if command -v fortune &>/dev/null && command -v cowthink &>/dev/null; then fortune -c | cowthink -r; fi
else
	[ "$(id -u)" -eq 0 ] && user_home="/root" || user_home="/home/${USER}"
	[ -f "${user_home}/.pfetch" ] && "${user_home}/.pfetch"
fi
timer_now () { date +%s%N; }
timer_start () { timer_start=${timer_start:-$(timer_now)}; }
timer_stop () {
	local delta_ns=$(($(timer_now) - timer_start))
	local delta_ms=$((delta_ns / 1000000))
	if ((delta_ms < 1)); then timer_show="$((delta_ns / 1000))us"
	elif ((delta_ms < 1000)); then timer_show="${delta_ms}ms"
	else local sec=$((delta_ms / 1000)); local ms=$((delta_ms % 1000)); timer_show="${sec}.$((ms / 100))s"; fi
	unset timer_start
}
set_prompt () {
	Last_Command=$?
	White='\[\e[01;37m\]' ; Red='\[\e[01;31m\]' ; Green='\[\e[01;32m\]' ; FancyX='\[\342\234\]\227' ; Checkmark='\[\342\234\]\223'
	PS1=" "
	if [[ $Last_Command == 0 ]]; then PS1+="$Red$Checkmark "; else PS1+="$White$FancyX "; fi
	timer_stop ; PS1+="$Green$timer_show "
	if [[ $(id -u) == 0 ]]; then PS1+="[$Red\A$Green] $Red\w "; else PS1+="[$White\A$Green] $Green\w "; fi
	PS1+='\[\e[00m\]'
}
trap 'timer_start' DEBUG
PROMPT_COMMAND='set_prompt'
