#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#chmod a+w /sys/class/backlight/intel_backlight/brightness &
setxkbmap -layout it &
numlockx &
xsetroot -cursor_name left_ptr &
wal -i ~/.wallpapers/ -o ~/.config/dunst/dunst-color.sh &
xset s 60 120
xss-lock -n "notify-send -u critical -t 5000 -- 'LOCKING in 2 min'" -- slock &
picom &
~/.config/low-battery.sh &
#~/.config/polybar/launch.sh

function start_bar {
	kill -f 'hide'
	pkill -f 'polybar'

	~/.config/polybar/launch.sh
	sleep 0.5
	~/.config/polybar/hide -d top -N 'polybar' --region 560x10+800+-100 -w & disown
	}

bspc monitor -d I II III IV V
start_bar "internal"

bspc config border_width         0
bspc config window_gap          15

#bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Termite desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Steam desktop='^3' state=floating
bspc rule -a Lutris desktop='^3'
bspc rule -a Minecraft* 1.16.5 desktop='^3' follow=on
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap desktop='^3' state=floating
bspc rule -a Pcmanfm desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a feh state=floating

. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color4"
