general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    # Prova ad accendere con Hyprland, se fallisce accende con Niri
    after_sleep_cmd = hyprctl dispatch dpms on || niri msg action power-on-monitors
}

listener {
    timeout = 300                                 # 5 minuti
    on-timeout = loginctl lock-session            # blocca lo schermo
}

listener {
    timeout = 330                                 # 5.5 minuti
    # Prova a spegnere con Hyprland, se fallisce spegne con Niri
    on-timeout = hyprctl dispatch dpms off || niri msg action power-off-monitors
    on-resume = hyprctl dispatch dpms on || niri msg action power-on-monitors
}
