backend = "kmeans"
color_space = "lab"
palette = "dark16"
check_contrast = true

[templates.hyprland]
template = "colors-hyprland.conf"
target = "~/.config/hypr/colors.conf"

[templates.kitty]
template = "colors-kitty.conf"
target = "~/.config/kitty/colors.conf"

[templates.fuzzel]
template = "colors-fuzzel.conf"
target = "~/.config/fuzzel/colors.ini"

[templates.waybar]
template = "colors-waybar.conf"
target = "~/.config/wallust/colors-waybar.css"

[templates.niri]
template = "config.kdl"
target = "~/.config/niri/config.kdl"
