@define-color background rgba({{background | rgb}}, 0.85); /* Leggera trasparenza 85% */
@define-color foreground #{{foreground}};
@define-color color0 #{{color0}};
@define-color color1 #{{color1}};
@define-color color2 #{{color2}};
@define-color color3 #{{color3}};
@define-color color4 #{{color4}};
@define-color color5 #{{color5}};
