general {
	lock_cmd = pidof hyprlock || bash -c "grim ~/.cache/screenlock.png && hyprlock"
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on || niri msg action power-on-monitors
}

listener {
	timeout = 300			# 5 minuti
	on-timeout = loginctl lock-session
}

listener {
	timeout = 330
	on-timeout = hyprctl dispatch dpms off || niri msg action power-off-monitors
	on-resume = hyprctl dispatch dpms on || niri msg action power-on-monitors
}
